---
- name: goland | download goland
  get_url:
    url: "https://download.jetbrains.com/go/goland-{{ goland_version }}.tar.gz"
    dest: "/tmp/goland-{{ goland_version }}.tar.gz"
    owner: root
    group: root
    mode: 0644
  tags:
  - goland

- name: goland | install goland
  unarchive:
    src: "/tmp/goland-{{ goland_version }}.tar.gz"
    dest: "/opt"
    creates: "/opt/goland-{{ goland_version }}"
    copy: false
  tags:
  - goland
