---
# ansible-playbook -vv -K playbook.yaml --diff --tags vbox
- name: main
  hosts: 127.0.0.1
  connection: local
  diff: yes
  become: yes
  roles:
  - role: rpm-fusion
    vars:
      fedora_version: 32
    tags: [fusion]
  - role: base
    tags: [base]
  - role: dev
    tags: [dev]
    vars:
      nfpm_ver: 1.8.0
  - role: look_and_feel
    tags: [look,never]
  - role: syncthing
    tags: [syncthing]
  - role: vscode
    tags: [vs]
  - role: sublime
    tags: [subl]
  - role: insync
    vars:
      fedora_version_fallback: 32
    tags: [insync]
  - role: vbox
    vars:
      fedora_version: 32
      vbox_version: 6.1
    tags: [vbox]
  - role: zsh
    vars:
      wakatime: true
    tags: [zsh]
  - role: devops-tools
    vars:
      terraform_ver: 0.12.20
      kubespy_ver: v0.5.1
      kind_ver: v0.8.1
      k9s_ver: v0.21.7
      kubectldebug_ver: 0.1.1
      helm_ver: v3.3.1
    tags: [devops]
  - role: sysctl
    tags: [sysctl]
  - role: iptables
    tags: [iptables]
  - role: crypt
    vars:
    - sops_ver: 3.6.1
    tags: [crypt]
  - role: other
    tags: [never,keychron]
  - role: lab
    tags: [lab]
  - role: obsidian
    tags: [obsidian]
    vars:
      obsidian_ver: 0.8.9
  - role: edu
    tags: [edu]
  - role: gnome-cleanup
    tags: [gnome-cleanup]
  - role: clouds
    tags: [clouds]
  - role: osint
    tags: [osint]
