---
# ansible-playbook -vv -K playbook.yaml --diff --tags vbox
- name: main
  hosts: all
  diff: yes
  become: yes
  tasks:
  -  debug: msg="{{ lookup('env','HOME') }}"
  roles:
  - role: rpm-fusion
    vars:
      fedora_version: 31
  - role: base
    vars:
      fedora_version: 31
    tags: [base]
  - role: gnome-cleanup
    tags: [gnome-cleanup]
  - role: dev
    tags: [dev]
  - role: media
    tags: [media]
  - role: look_and_feel
    tags: [look]
  - role: internet
    tags: [internet]
  - role: inkdrop
    tags: [inkdrop]
  - role: network-tools
    tags: [net]
  - role: syncthing
    tags: [syncthing]
  - role: k8s
    vars:
      kubespy_ver: v0.5.1
      kind_ver: v0.8.1
      k9s_ver: 0.19.7
      kubectldebug_ver: 0.1.1
      helm_ver: v2.14.3
    tags: [k8s]
  - role: gke
    tags: [gke]
  - role: vscode
    tags: [vs]
  - role: sublime
    tags: [subl]
  - role: docker
    vars:
      docker_compose_version: 1.25.5
    tags: [docker]
  - role: insync
    vars:
      fedora_version_fallback: 29
    tags: [insync]
  - role: vbox
    vars:
      fedora_version: 31
    tags: [vbox]
  - role: zsh
    vars:
      wakatime: true
    tags: [zsh]
  - role: term
    tags: [term, terminal]
  - role: devops-tools
    vars:
      terraform_ver: 0.12.20
      packer_ver: 1.5.6
      vagrant_ver: 2.2.9
    tags: [devops]
  - role: sysctl
    tags: [sysctl]
  - role: iptables
    tags: [iptables]
  - role: pycharm
    vars:
      pycharm_version: 2019.1.3
    tags: [pycharm,never]
  - role: crypt
    tags: [crypt]
  - role: other
    tags: [never,keychron]
  - role: security
    tags: [security,sec]
  - role: lab
    tags: [lab]
  - role: goland
    tags: [goland,never]
    vars:
      goland_version: 2020.1.2
