- name: Iptables |  Install iptables
  block:
  - name: Iptables | disable firewalld
    systemd:
        name: firewalld
        enabled: false
        state: stopped
        masked: true

  - name: Iptables | Install iptables-services
    dnf:
        name: iptables-services
        state: latest

  - name: Iptables | Enable iptables
    systemd:
        name: iptables
        enabled: true
        state: started
        daemon_reload: yes
  tags:
  - iptables
