- name: K8s | Instal kube tools
  block:
  - name: K8s | Copy k8s repo config
    yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      gpgcheck: yes
      enabled: yes

  - name: K8s | install kubectl
    dnf:
      name:
      - kubectl
      state: latest
    tags:
    - k8s-kubectl
  tags:
  - k8s
  - kubectl

- name: K8s | Install kind
  get_url:
    url: https://github.com/kubernetes-sigs/kind/releases/download/{{ kind_ver }}/kind-linux-amd64
    dest: "/usr/local/bin/kind"
    mode: 0755
  tags:
  - k8s
  - kind

- name: K8s | Install minkube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    force: true
    dest: "/usr/local/bin/minikube"
    mode: 0755
  tags:
  - k8s
  - minikube

- name: K8s | install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/{{ k9s_ver }}/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  tags:
  - k8s
  - k9s

- name: K8s | install kubespy
  unarchive:
    src: https://github.com/pulumi/kubespy/releases/download/{{ kubespy_ver }}/kubespy-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts:
    - --strip-components=2
    remote_src: yes
    mode: 0755
  tags:
  - k8s
  - kubespy

- name: K8s | install kubectl debug
  unarchive:
    src: https://github.com/aylei/kubectl-debug/releases/download/v{{ kubectldebug_ver }}/kubectl-debug_{{ kubectldebug_ver }}_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  tags:
  - k8s
  - kubectldebug

- name: install helm
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_ver }}-linux-amd64.tar.gz" #https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_ver }}-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
      - linux-amd64/helm
    #creates: /usr/local/bin/helm
  tags:
  - k8s
  - helm
