- name: zhs | Install zsh
  block:
  - name: zhs | install zsh
    dnf:
      name: zsh
      state: latest
  - name: zhs | Set user shell
    user:
      name: "{{ lookup('env','USER') }}"
      shell: /usr/bin/zsh
  tags:
  - zsh

- name: zhs | Install oh-my-zsh
  become: false
  block:
  - name: zhs | Download zsh installer
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/zsh-installer.sh
      mode: 0755

  - name: zhs | Execute the zsh-installer.sh
    shell: /tmp/zsh-installer.sh
    args:
      creates: "/home/{{ lookup('env','USER') }}/.oh-my-zsh"

  - name: zhs | Remove the zsh-installer.sh
    file:
      path: /tmp/zsh-installer.sh
      state: absent

  - name: zhs | Install zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  - name: zhs | Install zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  # https://medium.com/@alex285/get-powerlevel9k-the-most-cool-linux-shell-ever-1c38516b0caa
  - name: zhs | Install powerlevel9k
    git:
      repo: https://github.com/bhilburn/powerlevel9k.git
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/themes/powerlevel9k"
  - name: zhs | Copy .zshrc config
    copy:
      src: .zshrc
      dest: /home/{{ lookup('env','USER') }}/
      mode: 0644
  tags:
  - zsh
  - oh-my-zsh

