- name: zsh | Install zsh
  block:
  - name: zsh | install zsh
    dnf:
      name: zsh
      state: latest
  - name: zsh | Set user shell
    user:
      name: "{{ lookup('env','USER') }}"
      shell: /usr/bin/zsh
  tags:
  - zsh

- name: zsh | Install oh-my-zsh
  become: false
  block:
  - name: zsh | Download zsh installer
    get_url:
      url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      dest: /tmp/zsh-installer.sh
      mode: 0755

  - name: zsh | Execute the zsh-installer.sh
    shell: /tmp/zsh-installer.sh
    args:
      creates: "/home/{{ lookup('env','USER') }}/.oh-my-zsh"

  - name: zsh | Remove the zsh-installer.sh
    file:
      path: /tmp/zsh-installer.sh
      state: absent

  - name: zsh | Install zsh-syntax-highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      force: true
  - name: zsh | Install zsh-autosuggestions
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      force: true
  # https://medium.com/@alex285/get-powerlevel9k-the-most-cool-linux-shell-ever-1c38516b0caa
  - name: zsh | Install powerlevel9k
    git:
      repo: https://github.com/bhilburn/powerlevel9k.git
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/themes/powerlevel9k"
      force: true
  - name: zsh | Copy .zshrc config
    copy:
      src: "{{ item }}"
      dest: /home/{{ lookup('env','USER') }}/
      mode: 0644
    with_items:
    - .zshrc
    #- .zshrc_my
  tags:
  - zsh
  - oh-my-zsh

- name: zsh | install Wakatime
  become: false
  block:
  - name: zsh | install Wakatime zsh plugin
    pip:
      name: wakatime>=12.0
      extra_args: --user
      executable: pip3

  - name: zsh | install Wakatime zsh plugin
    git:
      repo: https://github.com/sobolevn/wakatime-zsh-plugin.git
      dest: "/home/{{ lookup('env','USER') }}/.oh-my-zsh/custom/plugins/wakatime"
      force: true
  when: wakatime|bool
  tags:
  - zsh
  - waka

- name: term  | install termtosvg
  become: false
  pip:
    name: termtosvg
    extra_args: --user
    executable: pip3
  tags:
  - termtosvg
  - term
