---
- name: googlecloud | install google cloud SDK
  block:
  - name: googlecloud | Install repo
    yum_repository:
      name: google-cloud-sdk
      description: Google Cloud SDK
      baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64"
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      gpgcheck: yes
      enabled: yes

  - name: googlecloud | install google-cloud-sdk
    dnf:
      name:
      - google-cloud-sdk
      state: latest
