- name: obsidian | Install obsidian
  become: false
  get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_ver }}/Obsidian-{{ obsidian_ver }}.AppImage"
    dest: "{{ lookup('env','HOME') }}/.local/bin/obsidian"
    mode: 0755

- name: obsidian | Create obsidian shortcut
  become: false
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Encoding=UTF-8
      Name=Obsidian
      Comment=Obsidian.md application
      Exec="{{ lookup('env','HOME') }}/.local/bin/obsidian"
      Terminal=false
      Categories=Application;
    dest: "/home/{{ lookup('env','USER') }}/.local/share/applications/obsidian.desktop"
