- name: Sysctl | Disable IPv6
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-disable-ipv6.conf
    reload: yes
  with_items:
  - { name: net.ipv6.conf.all.disable_ipv6 , value: 1 }
  - { name: net.ipv6.conf.default.disable_ipv6 , value: 1 }
  - { name: net.ipv6.conf.lo.disable_ipv6 , value: 1 }
  tags:
  - sysctl
  - kernel

- name: Sysctl | Enable ipv4 forwarding
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/10-enable-ipv4-forwarding.conf
    reload: yes
  with_items:
  - { name: net.ipv4.ip_forward , value: 1 }
  tags:
  - sysctl
  - kernel