---
- name: Crypt | install utils
  dnf:
    name:
    - keepass
    state: present
  tags:
  - crypt


- name: Crypt | Install veracrypt
  block:
  - name: Crypt | add veracrypt copr
    shell: dnf copr enable bgstack15/stackrpms -y
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:bgstack15:stackrpms.repo

  - name: Crypt | install veracrypt
    dnf:
      name: veracrypt
      state: latest
  tags:
  - crypt
  - veracrypt

- name: Crypt | Install encfs repo
  block:
  - name: Crypt | add veracrypt copr
    shell: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:moritzmolch:gencfsm/Fedora_30/home:moritzmolch:gencfsm.repo -y
    args:
      creates: /etc/yum.repos.d/home:moritzmolch:gencfsm.repo

  - name: Crypt | install encfs*
    dnf:
      name:
      - encfs
      - gnome-encfs-manager
      state: latest
  tags:
  - crypt
  - encfs