---
- name: Crypt | install utils
  dnf:
    name:
    - keepass
    state: present
  tags:
  - crypt

- name: Crypt | Install veracrypt
  block:
  - name: Crypt | add veracrypt copr
    shell: dnf copr enable bgstack15/stackrpms -y
    args:
      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:bgstack15:stackrpms.repo

  - name: Crypt | install veracrypt
    dnf:
      name: veracrypt
      state: latest
  tags:
  - crypt
  - veracrypt

- name: Crypt | Install SOPS
  get_url:
    url: "https://github.com/mozilla/sops/releases/download/v{{ sops_ver }}/sops-v{{ sops_ver }}.linux"
    dest: "/usr/local/bin/sops"
    mode: '0755'
    force: true
  tags:
  - sops
