- name: RPM Fusion | Install rpm fusion repos
  dnf:
    name:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
    state: present
    disable_gpg_check: true
  tags:
  - rpm_fusion
