  - name: Sublime | Install Sublime
    block:
    - name: Sublime | Add gpg key
      rpm_key:
        state: present
        key: "https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
    - name: Sublime | Add repo
      yum_repository:
        name: sublime-text
        description: Sublime Text - x86_64 - Stable
        baseurl: "https://download.sublimetext.com/rpm/stable/x86_64"
        gpgcheck: yes
        gpgkey: "https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
        enabled: yes
    - name: Sublime | install packets
      dnf:
        name:
        - sublime-merge
        - sublime-text
        state: latest
    tags:
    - subl
    - sublime
