- name: gnome-cleanup | Remove packets
  dnf:
    name:
    - abrt
    - gnome-software
    - PackageKit
    state: absent
  tags:
  - gnome-cleanup

- name: gnome-cleanup | Mask services
  become: false
  systemd:
    name: "{{ item }}"
    masked: true
    user: true
  with_items:
  - evolution-addressbook-factory
  - evolution-calendar-factory
  - evolution-source-registry
  - tracker-miner-apps
  - tracker-miner-fs
  - tracker-store
  - tracker-miner-rss
  - tracker-extract
  - tracker-writeback
  tags:
  - gnome-cleanup

- name: reset tracker
  shell: yes | tracker reset --hard
  tags:
  - gnome-cleanup

- name: gnome-cleanup | Disable speech-dispatcher
  lineinfile:
    path: /etc/speech-dispatcher/speechd.conf
    regexp: '^#.*DisableAutoSpawn'
    line: DisableAutoSpawn
  tags:
    - gnome-cleanup
