- name: Docker | Install docker-compose
  block:
  - name: Docker | Install docker repo
    shell: |
      dnf config-manager \
      --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    args:
      creates: /etc/yum.repos.d/docker-ce.repo

  - name: Docker | Install packets
    dnf:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: yes

  - name: Docker | Enable docker service
    systemd:
      name: docker
      state: started
      enabled: true
  tags:
  - docker

- name: Docker | Install docker-compose
  block:
  - name: Docker | Check current docker-compose version.
    command: docker-compose --version
    register: docker_compose_current_version
    changed_when: false
    failed_when: false

  - name: Docker | Delete existing docker-compose version if it's different.
    file:
      path: "/usr/bin/docker-compose"
      state: absent
    when: >
      docker_compose_current_version.stdout is defined
      and docker_compose_version not in docker_compose_current_version.stdout

  - name: Docker | Install Docker Compose (if configured).
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: "/usr/bin/docker-compose"
      mode: 0755
  tags:
  - docker
  - docker-compose

- name: Docker | install lazydocker
  shell: |
    curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: /usr/local/bin/lazydocker
  tags:
  - lazydocker
  - docker
