- name: Install docker-compose
  block:
  - name: Check current docker-compose version.
    command: docker-compose --version
    register: docker_compose_current_version
    changed_when: false
    failed_when: false

  - name: Delete existing docker-compose version if it's different.
    file:
      path: "/usr/bin/docker-compose"
      state: absent
    when: >
      docker_compose_current_version.stdout is defined
      and docker_compose_version not in docker_compose_current_version.stdout

  - name: Install Docker Compose (if configured).
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: "/usr/bin/docker-compose"
      mode: 0755
  tags:
  - docker
  - docker-compose

- name: install minio lazydocker
  shell: |
    curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  args:
    creates: /usr/local/bin/lazydocker
  tags:
  - lazydocker
  - docker