- name: Internet | install sysinternet softutils
  package:
    name:
    - chromium
    - deluge
    state: present

- name: Internet | Install chrome
  block:
  - name: Internet | Add chrome repo gpg key
    rpm_key:
      state: present
      key: https://dl-ssl.google.com/linux/linux_signing_key.pub
  - name: Internet | Add chrome repo
    yum_repository:
      name: google-chrome
      description: google-chrome
      baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      gpgcheck: yes
      gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
      enabled: yes
  - name:  Internet | install chrome
    dnf:
      name:
      - google-chrome-stable
      state: latest
