- name: Media | Install media
  dnf:
    name:
    - gstreamer-plugins-*
    - gstreamer1-plugins-*
    - minidlna
    - flameshot
    - peek
    - rawtherapee
    - inkscape
    - gimp
    - vlc
    - ffmpeg-libs
    - youtube-dl
    - ImageMagick
    - audacious
    - hydrapaper
    - pinta
    state: latest

- name: Media | Cleanup
  dnf:
    name:
    - rhythmbox
    - cheese
    state: absent

- name: Media | audacious winamp skin
  copy:
    src: "{{ item }}"
    dest: /usr/share/audacious/Skins/
  with_fileglob:
  - "*.wsz"
