
- name: Network | install packets
  package:
    name:
    - wireshark
    - wireshark-cli
    state: latest

- name: Network | Adding user to group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: wireshark
    append: yes

- name: Network | Install network utils
  package:
    name:
    - iftop
    - ifstat
  # - macchanger
    - bind-utils
    - iperf
    - ethtool
    - nmap
    state: latest
