# - name: Network | Adding user to group
#   user:
#     name: "{{ lookup('env','USER') }}"
#     groups: wireshark
#     append: yes

- name: network | install network utils
  package:
    name:
    - iftop
    - ifstat
    - macchanger
    - bind9-dnsutils
    - iperf
    - ethtool
    - nmap
    - shadowsocks-libev
    - tsocks
    - wireshark
    - wireshark-common
    state: latest
