- name: Vim | Install vim and plugins
  package:
    name:
    - ranger
    - vim
    - vim-syntastic-go
    - vim-syntastic-rst
    - vim-syntastic-xml
    - vim-syntastic-zsh
    - vim-syntastic-text
    - vim-syntastic-yaml
    - vim-syntastic-ansible
    - vim-syntastic-python
    - vim-syntastic-json
    state: latest

- name: Vim | Vim config
  copy:
    content: |
      colorscheme industry
      set number
      syntax on
      set hlsearch
      set et
      set sw=2 ts=2 sts=2
    dest: "{{ lookup('env','HOME') }}/.vimrc"
