- name: Look_and_feel | dconf
  become: false
  block:
  - name: Look_and_feel | install python package
    pip:
      name: psutil
      extra_args: --user
      executable: pip3

  - name: Look_and_feel | Read currently available keyboard layouts in Gnome
    become: false
    dconf:
      key: "{{ item.key }}"
      state: present
      value: "{{ item.value }}"
    with_items:
    - { key: "/org/gnome/desktop/wm/preferences/titlebar-font", value: "'Fira Sans Bold 11'"}
    - { key: "/org/gnome/desktop/interface/document-font-name", value: "'Fira Sans 11'"}
    - { key: "/org/gnome/desktop/interface/font-name", value: "'Fira Sans 11'"}
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'Source Code Pro 9'"}

    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Arc-Darker-solid'"}
    - { key: "/org/gnome/shell/extensions/user-theme", value: "'Arc-Dark-solid'"}

    - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'Paper'"}
    - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Papirus-Light'"}

    - { key: "/org/gnome/nautilus/preferences/default-folder-viewer", value: "'list-view'"}
    - { key: "/org/gnome/nautilus/preferences/default-sort-order", value: "'type'"}
    - { key: "/org/gnome/nautilus/list-view/default-visible-columns", value: "[ 'name', 'size', 'date_modified', 'type', 'permissions', 'star']"}
    - { key: "/org/gnome/nautilus/icon-view/default-zoom-level", value: "'small'"}
    - { key: "/org/gnome/nautilus/list-view/default-zoom-level", value: "'small'"}
    - { key: "/org/gnome/nautilus/preferences/default-folder-viewer", value: "'list-view'"}
    - { key: "/org/gnome/nautilus/preferences/default-sort-order", value: "'type'"}


    # Dialog box
    - { key: "/org/gtk/Settings/FileChooser/sort-directories-first", value: "'true'"}


    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "'appmenu:minimize,maximize,close'"}

    - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "['grp:alt_shift_toggle']"}

    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true"}

    - { key: "/system/locale/region", value: "'ru_RU.UTF-8'"}

  #workaround
  # [WARNING]: The value [['xkb', 'ru'], ['xkb', 'us']] (type list) in a string field was converted to "[['xkb', 'ru'], ['xkb', 'us']]" (type string). If this does not look like what you expect, quote the
  # entire value to ensure it does not change.
  - name: Look_and_feel | Set mru-sources
    become: false
    dconf:
      key: "/org/gnome/desktop/input-sources/mru-sources"
      state: present
      value: "[('xkb', 'ru'), ('xkb', 'us')]"
  - name: Look_and_feel | Set sources
    become: false
    dconf:
      key: "/org/gnome/desktop/input-sources/sources"
      state: present
      value: "[('xkb', 'ru'), ('xkb', 'us')]"
