- name: Look_and_feel | Paper icon install
  block:
  - name: Look_and_feel | Add gpg key for paper icon repo
    rpm_key:
      state: present
      key: "https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key"
  - name: Look_and_feel | Add paper icon repo
    yum_repository:
      name: home:snwh:paper
      description: Paper Project (Fedora_25)
      baseurl: "http://download.opensuse.org/repositories/home:/snwh:/paper/Fedora_25/"
      gpgkey: "http://download.opensuse.org/repositories/home:/snwh:/paper/Fedora_25/repodata/repomd.xml.key"
      gpgcheck: yes
      enabled: yes
  - name: Look_and_feel | install paper icon theme
    dnf:
      name:
      - paper-icon-theme
      state: latest
  tags:
  - look_and_feel
  - paper

- name: Look_and_feel | Install ARC theme && gnome tweak
  dnf:
    name:
    - arc-theme
    - gnome-tweak-tool
    state: present
  tags:
  - look_and_feel

- name: Look_and_feel | Install gnome ext
  block:
  - name: Look_and_feel | Install gnome ext installer
    get_url:
      url:  https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/ubuntugnome/gnomeshell-extension-manage
      dest: /usr/local/bin/gnomeshell-extension-manage
      mode: 0755

  - name: Look_and_feel | Install gnome exts
    become: false
    shell: |
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 6     --version latest   #Applications Menu by fmuellner
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 307   --version latest   #Dash to Dock by michele_g
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 615   --version latest   #KStatusNotifierItem/AppIndicator Support by 3v1n0
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 1357  --version latest   #Notes by Maestroschan
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 8     --version latest   #Places Status Indicator by fmuellner
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 120   --version latest   #system-monitor by Cerin
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 19    --version latest   #User Themes by fmuellner
      /usr/local/bin/gnomeshell-extension-manage --install --extension-id 690   --version latest   #Easy screencast
    notify:
    - reload gnome-shell
  tags:
  - gnome
  - look_and_feel

- name: Look_and_feel | dconf
  become: false
  block:
  - name: Look_and_feel | install python package
    pip:
      name: psutil
      extra_args: --user
      executable: pip3

  - name: Look_and_feel | Read currently available keyboard layouts in Gnome
    dconf:
      key: "{{ item.key }}"
      state: present
      value: "{{ item.value }}"
    with_items:
    - { key: "/org/gnome/desktop/wm/preferences/titlebar-font", value: "'Fira Sans Bold 11'"}
    - { key: "/org/gnome/desktop/interface/document-font-name", value: "'Fira Sans 11'"}
    - { key: "/org/gnome/desktop/interface/font-name", value: "'Fira Sans 11'"}
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'Source Code Pro 9'"}

    - { key: "/org/gnome/desktop/interface/gtk-theme", value: "'Arc-Darker-solid'"}
    - { key: "/org/gnome/shell/extensions/user-theme", value: "'Arc-Dark-solid'"}

    - { key: "/org/gnome/desktop/interface/cursor-theme", value: "'Paper'"}
    - { key: "/org/gnome/desktop/interface/icon-theme", value: "'Paper'"}

    - { key: "/org/gnome/nautilus/preferences/default-folder-viewer", value: "'list-view'"}
    - { key: "/org/gnome/nautilus/preferences/default-sort-order", value: "'type'"}
    - { key: "/org/gnome/nautilus/list-view/default-visible-columns", value: "[ 'name', 'size', 'date_modified', 'type', 'permissions', 'star']"}
    - { key: "/org/gnome/nautilus/icon-view/default-zoom-level", value: "'small'"}
    - { key: "/org/gnome/nautilus/list-view/default-zoom-level", value: "'small'"}
    - { key: "/org/gnome/nautilus/preferences/default-folder-viewer", value: "'list-view'"}
    - { key: "/org/gnome/nautilus/preferences/default-sort-order", value: "'type'"}


    - { key: "/org/gnome/desktop/wm/preferences/button-layout", value: "'appmenu:minimize,maximize,close'"}

    - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "['grp:alt_shift_toggle']"}

    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true"}

    - { key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme", value: "false"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity", value: "0.0"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dock-position", value: "'BOTTOM'"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size", value: "32"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme", value: "false"}
    - { key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme", value: "false"}
    #calendar
    - { key: "/org/gnome/evolution/calendar/week-start-day-name", value: "'monday'"}
    #system-monitor
    - { key: "/org/gnome/shell/extensions/system-monitor/cpu-show-text", value: "false"}
    - { key: "/org/gnome/shell/extensions/system-monitor/cpu-graph-width", value: "32"}
    - { key: "/org/gnome/shell/extensions/system-monitor/disk-show-text", value: "false"}
    - { key: "/org/gnome/shell/extensions/system-monitor/disk-graph-width", value: "32"}
    - { key: "/org/gnome/shell/extensions/system-monitor/memory-show-text", value: "false"}
    - { key: "/org/gnome/shell/extensions/system-monitor/memory-graph-width", value: "32"}
    - { key: "/org/gnome/shell/extensions/system-monitor/swap-show-text", value: "false"}
    - { key: "/org/gnome/shell/extensions/system-monitor/swap-graph-width", value: "32"}
    - { key: "/org/gnome/shell/extensions/system-monitor/net-show-text", value: "false"}
    - { key: "/org/gnome/shell/extensions/system-monitor/net-graph-width", value: "32"}

    - { key: "/system/locale/region", value: "'ru_RU.UTF-8'"}

  #workaround
  # [WARNING]: The value [['xkb', 'ru'], ['xkb', 'us']] (type list) in a string field was converted to "[['xkb', 'ru'], ['xkb', 'us']]" (type string). If this does not look like what you expect, quote the
  # entire value to ensure it does not change.
  - name: Look_and_feel | Set mru-sources
    dconf:
      key: "/org/gnome/desktop/input-sources/mru-sources"
      state: present
      value: "[('xkb', 'ru'), ('xkb', 'us')]"
  - name: Look_and_feel | Set sources
    dconf:
      key: "/org/gnome/desktop/input-sources/sources"
      state: present
      value: "[('xkb', 'ru'), ('xkb', 'us')]"
    tags:
    - dconf
    - look_and_feel

- name: Look_and_feel | Install fonts
  dnf:
    name:
    - mozilla-fira-*
    - google-noto-sans-fonts
    state: present
  tags:
  - fonts

- name: Look_and_feel | install Nerd fonts
  become: false
  block:
  - debug: msg={{ nerd_fonts }}
  - name: Look_and_feel | Create font dirs in "/home/{{ lookup('env','USER') }}/.local/share/fonts/"
    file:
      path: "/home/{{ lookup('env','USER') }}/.local/share/fonts/{{ item.font }}"
      state: directory
    with_items: "{{nerd_fonts}}"
    notify:
    - reload font cache
  - name: Look_and_feel | Install nerd fonts
    unarchive:
      src: "{{ item.link }}"
      dest: "/home/{{ lookup('env','USER') }}/.local/share/fonts/{{ item.font }}"
      remote_src: yes
      mode: 0644
    with_items: "{{nerd_fonts}}"
    notify:
    - reload font cache
  vars:
    nerd_fonts:
    - { font: "DroidSansMono", link: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/DroidSansMono.zip"}
    - { font: "FiraCode", link: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip"}
    - { font: "Inconsolata", link: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Inconsolata.zip"}
  tags:
  - nerd
  - fonts
  - look_and_feel
