- name: Git | Create global .gitignore
  become: false
  copy:
    content: |
      .envrc
      .terraform
      .vagrant
      *.log
      *.retry
      *.tfstate
      secret*
    dest: "/home/{{ lookup('env','USER') }}/.gitignore"

- name: Git | Configure git settings
  become: false
  git_config:
    name:  "{{ item.name }}"
    scope: "{{ item.scope }}"
    value: "{{ item.value }}"
  with_items:
  - name:  core.excludesfile
    scope: global
    value: "~/.gitignore"
  - name:  alias.lg
    scope: global
    value: "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
  - name:  alias.fire
    scope: global
    value: >
         !sh -c "git checkout -b wip/fire/$USER && \
         git stage -A && \
         git commit -m wip-fire-alert && \
         git push origin wip/fire/$USER"
  - name:  blame.coloring
    scope: global
    value: highlightRecent
  - name:  color.blame.highlightRecent
    scope: global
    value: blue,12 month ago,white,1 month ago,red
  - name:  alias.lf
    scope: global
    value: log -p -M --follow --stat --
