- name: Git | Create global .gitignore
  become: false
  copy:
    content: |
      .envrc
      .terraform
      .vagrant
      *.log
      *.retry
      *.tfstate
      secret*
    dest: "/home/{{ lookup('env','USER') }}/.gitignore"

- name: Git | Configure git settings
  become: false
  git_config:
    name: core.excludesfile
    scope: global
    value: "~/.gitignore"
