  - name: Syncthing
    block:
    - name: Syncthing | install packets
      dnf:
        name:
        - syncthing
        state: present
    - name: Syncthing | Copy systemd unit
      copy:
        content: |
            [Unit]
            Description=Syncthing - Open Source Continuous File Synchronization for %I
            Documentation=man:syncthing(1)
            After=network.target

            [Service]
            User=%i
            ExecStart=/usr/bin/syncthing -no-browser -gui-address="127.0.0.1:8384" -no-restart -logflags=0
            Restart=on-failure
            SuccessExitStatus=3 4
            RestartForceExitStatus=3 4

            [Install]
            WantedBy=multi-user.target
        dest: /etc/systemd/system/syncthing@.service
    - name: Syncthing | Add repo
      systemd:
        name: syncthing@user
        daemon_reload: yes
        enabled: true
        state: started
    tags:
    - syncthing
